blueprint:
  name: ZHA - Signify RDM001
  description: Control anything using Signify RDM001 double rocker type switch (mode 2)

  domain: automation
  input:
    remote:
      name: Remote
      description: Signify switch to use
      selector:
        device:
          integration: zha
          manufacturer: Signify Netherlands B.V.
          model: RDM001
    button_left_press:
      name: Left button press
      description: Action to run on press of left button
      default: []
      selector:
        action:
    button_left_release:
      name: Left button release
      description: Action to run on release of left button
      default: []
      selector:
        action:

    button_right_press:
      name: Right button press
      description: Action to run on press of right button
      default: []
      selector:
        action:
    button_right_release:
      name: Right button release
      description: Action to run on release of right button
      default: []
      selector:
        action:

mode: restart
max_exceeded: silent

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote

action:
  - variables:
      command: "{{ trigger.event.data.command }}"
      cluster_id: "{{ trigger.event.data.cluster_id }}"
      endpoint_id: "{{ trigger.event.data.endpoint_id }}"
      args: "{{ trigger.event.data.args }}"
  - choose:
      - conditions:
          - "{{ command == 'left_press_release' }}"
        sequence: !input button_left_release

      - conditions:
          - "{{ command == 'left_short' }}"
        sequence: !input button_left_press

  - choose:
      - conditions:
          - "{{ command == 'right_press_release' }}"
        sequence: !input button_right_release

      - conditions:
          - "{{ command == 'right_short' }}"
        sequence: !input button_right_press
